M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Wed 29 Nov 2023 01:05:21 PM PST
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2023-11-29T13:05:21-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.2362
%
G90
G05
T1
X41339Y-25591
X41339Y-37402
X53150Y-25591
X53150Y-37402
T0
M30
